home/urls.py
from django.urls import path

from .import views



urlpatterns = [
    path('', views.index, name='index'),
    
]

interior_imaaratdesign/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import home
from home import views 
from django.utils.translation import gettext_lazy as _

from django.views.generic import RedirectView
urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('logout/',RedirectView.as_view(url = '/admin/logout/')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path(('contactus/'), views.contactus, name='contactus'),
    path(('faqs/'), views.faqs, name='faqs'),
    path(('product/'), views.product, name='product'),
    path(('brand/'), views.BRAND, name='brand'),
    path(('gallery/'), views.Gallery_Media, name='gallery'),

    path(('about/'), views.aboutus, name='aboutus'),
    path(('our-team/'), views.Our_Team, name='our-team'),
    path(('vision-mission/'), views.Vision_Mission, name='vision-mission'),
    path(('director-desk/'), views.DirectorDesk, name='director-desk'),


    path(('architecture/'), views.Architecture, name='architecture'),
    path(('construction/'), views.Construction, name='construction'),
    path(('interior/'), views.Interior, name='interior'),
    path(('landscape/'), views.Landscape, name='landscape'),
    path(('turnkey/'), views.Turnkey, name='turnkey'),


    path(('blog/'), views.BLOG, name='blog'),
    path(('real-estate/'), views.REALESTATE, name='real-estate'),

    path(('product/'), views.product, name='product'),
    path('product_details/<slug:slug>', views.product_details, name='product_details'),

    path(('complate_project/'), views.Complate_project, name='complate_project'),
    path(('ongoing_project/'), views.Ongoing_project, name='ongoing_project'),
    path(('upcoming_project/'), views.Upcoming_project, name='Upcoming_project'),
    path('project_details/<slug:slug>', views.project_details, name='project_details'),

    path(('service/'), views.service, name='service'),
    path('service_details/<slug:slug>', views.service_details, name='service_details'),
                                                                                                                                                                                                 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.utils.html import mark_safe
# Create your models here.
from django.db.models import Avg, Count
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.db.models.signals import pre_save

from django.utils.text import slugify
# Create your models here.


class Project(models.Model):    
    Project_Type = (
        ('COMPLATE', 'COMPLATE'),
        ('ONGOING', 'ONGOING'),
        ('UPCOMING', 'UPCOMING'),
    )

    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=1255)
    description = models.TextField(max_length=1255)
    image=models.ImageField(upload_to='images/',null=False)
    detail=RichTextUploadingField()
    slug = models.SlugField(null=True,blank=True, unique=True,max_length=250)
    Project_Type=models.CharField(max_length=10,choices=Project_Type)
    featured_project = models.BooleanField(default=False)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural='2. Project'


    ## method to create a fake table field in read only mode
    def image_tag(self):
        if self.image.url is not None:
            return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
        else:
            return ""

    def save(self , *args , **kwargs):
        self.slug = slugify(self.title)
        super(Project ,self).save(*args , **kwargs)


    def get_absolute_url(self):
        return reverse('project_details', kwargs={'slug': self.slug})

    def avaregereview(self):
        reviews = Comment.objects.filter(product=self, status='True').aggregate(avarage=Avg('rate'))
        avg=0
        if reviews["avarage"] is not None:
            avg=float(reviews["avarage"])
        return avg

    def countreview(self):
        reviews = Comment.objects.filter(product=self, status='True').aggregate(count=Count('id'))
        cnt=0
        if reviews["count"] is not None:
            cnt = int(reviews["count"])
        return cnt

class Project_Images(models.Model):
    product=models.ForeignKey(Project,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title


class Service(models.Model):    
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )

    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=1255)
    description = models.TextField(max_length=1255)
    image=models.ImageField(upload_to='images/',null=False)
    detail=RichTextUploadingField()
    slug = models.SlugField(null=True,blank=True, unique=True,max_length=250)
    status=models.CharField(max_length=10,choices=STATUS)
    featured_project = models.BooleanField(default=False)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural='3. Service'


    ## method to create a fake table field in read only mode
    def image_tag(self):
        if self.image.url is not None:
            return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
        else:
            return ""

    def save(self , *args , **kwargs):
        self.slug = slugify(self.title)
        super(Service ,self).save(*args , **kwargs)


    def get_absolute_url(self):
        return reverse('service_details', kwargs={'slug': self.slug})

    def avaregereview(self):
        reviews = Comment.objects.filter(product=self, status='True').aggregate(avarage=Avg('rate'))
        avg=0
        if reviews["avarage"] is not None:
            avg=float(reviews["avarage"])
        return avg

    def countreview(self):
        reviews = Comment.objects.filter(product=self, status='True').aggregate(count=Count('id'))
        cnt=0
        if reviews["count"] is not None:
            cnt = int(reviews["count"])
        return cnt

class Service_Images(models.Model):
    product=models.ForeignKey(Service,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title


class Product(models.Model):    
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )

    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=1255)
    description = models.TextField(max_length=1255)
    image=models.ImageField(upload_to='images/',null=False)
    detail=RichTextUploadingField()
    slug = models.SlugField(null=True,blank=True, unique=True,max_length=250)
    status=models.CharField(max_length=10,choices=STATUS)
    featured_project = models.BooleanField(default=False)
    Top_Deals_Of_The_Day = models.BooleanField(default=False)
    Top_Selling_Products = models.BooleanField(default=False)
    Recommended_For_You = models.BooleanField(default=False)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural='1. Product'


    ## method to create a fake table field in read only mode
    def image_tag(self):
        if self.image.url is not None:
            return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
        else:
            return ""

    def save(self , *args , **kwargs):
        self.slug = slugify(self.title)
        super(Product ,self).save(*args , **kwargs)


    def get_absolute_url(self):
        return reverse('product_details', kwargs={'slug': self.slug})

    def avaregereview(self):
        reviews = Comment.objects.filter(product=self, status='True').aggregate(avarage=Avg('rate'))
        avg=0
        if reviews["avarage"] is not None:
            avg=float(reviews["avarage"])
        return avg

    def countreview(self):
        reviews = Comment.objects.filter(product=self, status='True').aggregate(count=Count('id'))
        cnt=0
        if reviews["count"] is not None:
            cnt = int(reviews["count"])
        return cnt

class Images(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title


class Comment(models.Model):
    STATUS = (
        ('New', 'New'),
        ('True', 'True'),
        ('False', 'False'),
    )
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50, blank=True)
    comment = models.CharField(max_length=250,blank=True)
    rate = models.IntegerField(default=1)
    ip = models.CharField(max_length=20, blank=True)
    status=models.CharField(max_length=10,choices=STATUS, default='New')
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
    
    class Meta:
        verbose_name_plural='4. Comment'

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']

home/views.py
from django.shortcuts import render,redirect
from home.models import *
from product.models import *


# Create your views here.
def index(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]
    slider = Slider.objects.all().order_by('-id')[0:6]
    about = About_Page.objects.all().order_by('-id')[0:1]
    contentclider = Content_Slider.objects.all().order_by('-id')
    service = Service.objects.all().order_by('-id')

    faq = FAQ.objects.all().order_by('-id')[0:6]


    
    

    page="home"
    context={
        'setting':setting,
        'slider':slider,
        'about':about,
        'contentclider':contentclider,
        'faq':faq,
        'service':service,
    }

    return render(request,'main/index.html',context)

def aboutus(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]
    about = About_Page.objects.all().order_by('-id')[0:1]
    slider = Slider.objects.all().order_by('-id')[0:6]
    
    

    page="home"
    context={
        'setting':setting,
        'slider':slider,
        'about':about,
    }

    return render(request,'main/about.html',context)



def product(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]
    product = Product.objects.all().order_by('?')

    page="home"
    context={
        'setting':setting,
        'product':product,
    }
    return render(request,'main/product/product.html',context)

def product_details(request,slug): 
    setting = Setting.objects.all().order_by('-id')[0:1]

    product = Product.objects.filter(slug = slug)
    if product.exists():
        product = Product.objects.get(slug = slug)
    else :
        return redirect('404')
    context = {

        'product': product,
        'setting': setting,
    }   
     
    return render(request, 'main/product/product-details.html',context)

#-------------------------Projects---------------------------------------------------------
def Complate_project(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]
    project = Project.objects.filter(Project_Type= 'COMPLATE').order_by('-id')


    page="home"
    context={
        'setting':setting,
        'project':project,
    }
    return render(request,'main/project/complate-projects.html',context)

def Ongoing_project(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]
    project = Project.objects.filter(Project_Type= 'ONGOING').order_by('-id')


    page="home"
    context={
        'setting':setting,
        'project':project,
    }
    return render(request,'main/project/Ongoing-Projects.html',context)

def Upcoming_project(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]
    project = Project.objects.filter(Project_Type = 'UPCOMING').order_by('-id')

    page="home"
    context={
        'setting':setting,
        'product':product,
    }
    return render(request,'main/project/Upcoming-Projects.html',context)

def project_details(request,slug): 
    setting = Setting.objects.all().order_by('-id')[0:1]

    project = Project.objects.filter(slug = slug)
    if project.exists():
        project = Project.objects.get(slug = slug)
    else :
        return redirect('404')
    context = {

        'project': project,
        'setting': setting,
    }   
     
    return render(request, 'main/project/product-details.html',context)

#-------------------------Projects---------------------------------------------------------


def service(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]
    service = Service.objects.all().order_by('?')

    page="home"
    context={
        'setting':setting,
        'service':service,
    }
    return render(request,'main/services/services.html',context)

def service_details(request,slug): 
    setting = Setting.objects.all().order_by('-id')[0:1]

    service = Service.objects.filter(slug = slug)
    if service.exists():
        service = Service.objects.get(slug = slug)
    else :
        return redirect('404')
    context = {

        'service': service,
        'setting': setting,
    }   
     
    return render(request, 'main/services/services-details.html',context)



def faqs(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/FQA.html',context)

def contactus(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/contactus.html',context)

def BRAND(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/BRAND.html',context)

def BLOG(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/blog.html',context)

def Gallery_Media(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]
    gallery = Gallery.objects.all().order_by('?')


    page="home"
    context={
        'setting':setting,
        'gallery':gallery,
    }
    return render(request,'main/Gallery.html',context)


def Our_Team(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/OurtTeam.html',context)


def Vision_Mission(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/Vision-Mission.html',context)

def DirectorDesk(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/director-desk.html',context)


#=====================Service Area=================================
def Architecture(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/Architecture.html',context)


def Construction(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/Construction.html',context)


def Interior(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/Interior.html',context)



def Landscape(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/Landscape.html',context)


def Turnkey(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/Turnkey.html',context)


def REALESTATE(request):    
    setting = Setting.objects.all().order_by('-id')[0:1]

    page="home"
    context={
        'setting':setting,
    }
    return render(request,'main/Real_Estate.html',context)

home/templates/main/project/Ongoing-Projects.html
{% extends "base.html" %}
{% load static %}

<br>


{% block body %}
 <!--============================== Breadcumb ============================== -->
 <div class="breadcumb-wrapper " data-bg-src="{% static '' %}assets/img/bg/breadcumb-bg.jpg">
    <div class="container">
        <div class="breadcumb-content">
            <h1 class="breadcumb-title">Complate Projects</h1>
            <ul class="breadcumb-menu">
                <li><a href="/">Home</a></li>
            </ul>
        </div>
    </div>
</div>

<!--============================== Construction Area  ==============================-->
{% for i in project %}
<div class="overflow-hidden overflow-hidden space" id="about-sec">
    <div class="container">
        <div class="row">
            <div class="col-xl-6">
                <div class="img-box3">
                    <div class="img1">
                        <img src="{{i.image.url}}" alt="About">
                    </div>
                </div>
            </div>
            <div class="col-xl-6">
                <div class="title-area mb-20 pe-xl-5 me-xl-5">
                    <h2 class="sec-title mb-20"><a href="{{i.get_absolute_url}}">{{i.title}}</a></h2>
                </div>
                <p class="sec-text mb-30" align="justify">{{i.description}}</p>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock body %}

home/templates/main/project/Upcoming-Projects.html
{% extends "base.html" %}
{% load static %}

<br>


{% block body %}
 <!--============================== Breadcumb ============================== -->
 <div class="breadcumb-wrapper " data-bg-src="{% static '' %}assets/img/bg/breadcumb-bg.jpg">
    <div class="container">
        <div class="breadcumb-content">
            <h1 class="breadcumb-title">Complate Projects</h1>
            <ul class="breadcumb-menu">
                <li><a href="/">Home</a></li>
            </ul>
        </div>
    </div>
</div>

<!--============================== Construction Area  ==============================-->
{% for i in project %}
<div class="overflow-hidden overflow-hidden space" id="about-sec">
    <div class="container">
        <div class="row">
            <div class="col-xl-6">
                <div class="img-box3">
                    <div class="img1">
                        <img src="{{i.image.url}}" alt="About">
                    </div>
                </div>
            </div>
            <div class="col-xl-6">
                <div class="title-area mb-20 pe-xl-5 me-xl-5">
                    <h2 class="sec-title mb-20"><a href="{{i.get_absolute_url}}">{{i.title}}</a></h2>
                </div>
                <p class="sec-text mb-30" align="justify">{{i.description}}</p>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock body %}

home/templates/main/project/complate-projects.html
{% extends "base.html" %}
{% load static %}

<br>


{% block body %}
 <!--============================== Breadcumb ============================== -->
 <div class="breadcumb-wrapper " data-bg-src="{% static '' %}assets/img/bg/breadcumb-bg.jpg">
    <div class="container">
        <div class="breadcumb-content">
            <h1 class="breadcumb-title">Complate Projects</h1>
            <ul class="breadcumb-menu">
                <li><a href="/">Home</a></li>
            </ul>
        </div>
    </div>
</div>

<!--============================== Construction Area  ==============================-->
{% for i in project %}
<div class="overflow-hidden overflow-hidden space" id="about-sec">
    <div class="container">
        <div class="row">
            <div class="col-xl-6">
                <div class="img-box3">
                    <div class="img1">
                        <img src="{{i.image.url}}" alt="About">
                    </div>
                </div>
            </div>
            <div class="col-xl-6">
                <div class="title-area mb-20 pe-xl-5 me-xl-5">
                    <h2 class="sec-title mb-20"><a href="{{i.get_absolute_url}}">{{i.title}}</a></h2>
                </div>
                <p class="sec-text mb-30" align="justify">{{i.description}}</p>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock body %}

home/templates/main/project/product-details.html
{% extends "base.html" %}
{% load static %}

<br>


{% block body %}
<!--============================== Breadcumb ============================== -->
<div class="breadcumb-wrapper " data-bg-src="{{project.image.url}}" style="height: 600px;">
    <div class="container">
        <div class="breadcumb-content">
            <h1 class="breadcumb-title">{{project.title}}</h1>
            <ul class="breadcumb-menu">
                <li><a href="/">Home</a></li>
                <li>Project</li>
            </ul>
        </div>
    </div>
</div>

<!--============================== Project Area ==============================-->

 <!--============================== Photo Area ==============================-->
 <section class="space">
    <div class="container">
        <div class="title-area text-center mb-40">
            <span class="sub-title">Photo</span>
            <h2 class="sec-title">Let’s See Our Latest Photo</h2>
        </div>
        
        <div class="row gallery-row filter-active">
            <!-- Single Item -->
            {% for i in project.images_set.all %}
            <div class="col-md-6 col-xl-auto filter-item cat1">
                <div class="project-box">
                    <div class="project-box-img">
                        <img src="{{i.image.url}}" style="width:385px;height:385px;" alt="project image">
                    </div>
                    <div class="project-box-content">
                        <p class="project-subtitle">Deepak</p>
                        <h3 class="box-title"><a>Complex</a></h3>
                        <a href="{{i.image.url}}" class="gallery-btn popup-image"><i class="fa-regular fa-plus"></i></a>
                    </div>
                </div>
            </div>    
            {% endfor %}         
        </div>           
    </div>
    <div class="container">
        <div class="project-details">
            <div class="page-img">
                
            </div>
            <ul class="project-details-wrap">
                
            </ul>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="page-content style2 mb-40">
                    <h3 class="h3 page-title">Product Overview</h3>
                    <p class="sec-text mb-25" align="justify">{{project.description}}</p>
                </div>
            </div>
            <div class="col-lg-4">
                <aside class="sidebar-area style2 pt-0">
                    <div class="widget widget_offer  " data-overlay="title" data-opacity="9" data-bg-src="{% static '' %}assets/img/bg/widget_bg_1.jpg">
                        <div class="offer-banner">
                            <div class="offer">
                                <span class="sub-title">Contact for inquery</span>
                                <h6 class="box-title">Need Help? We Are Here To Help You</h6>
                                <a href="{% url "contactus" %}" class="th-btn style1">Get A Quote</a>
                            </div>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
        <div class="page-content style2">
            {{project.detail |safe }}
        </div>
    </div>
</section>



{% endblock body %}